name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # skip if is it pushed by fluxcd
    if: ${{ !contains(github.event.commits.*.author.name, 'fluxcd') }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      -
        name: test
        run: |
          go list ./... | grep -v "github.com/gotti/meshover/wireguard" | xargs go test -cover
